services:
  unsloth:
    build:
      dockerfile: Dockerfile
    environment:
      HF_TOKEN: <your hf token>
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 'all'
    working_dir: /app
    volumes:
      - "local_path:/app"
      - "local_path/models:/app/models"
    tty: true
